<?php
include('header.php');
echo $hh;
?>
     <!-- LOAD PAGE -->
     <div class="animationload">
        <div class="loader"></div>
    </div>

    <!-- BACK TO TOP SECTION -->
    <a href="#0" class="cd-top cd-is-visible cd-fade-out">Top</a>

   

    <!-- BANNER -->
    <div class="section banner-page" data-background="images/banner-common.png">
        <div class="content-wrap pos-relative">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex bd-highlight mb-3">
                            <div class="title-page">About Us</div>
                        </div>
                        <div class="d-flex bd-highlight mb-3">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb ">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                    <li class="breadcrumb-item active" aria-current="page">About Us</li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- WELCOME TO LAWE -->
    <div class="section">
        <div class="content-wrap">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <h2 class="section-heading">
                            Namaste!
                        </h2>
                        <p class="subheading mb-4">"We assist in sustaining rural development through technology"</p>
                        <p>
                        The  The web-site is essential to support Digital India making Rural people's life easy and hassle-free, and helping them in development.
                        </p>
                        <p>
                            The Gram Panchayat web-site is specially developed for Gram Panchayat to support Digital India. It helps you to run all Gram Panchayat's operations smoothly and makes the process very easy. All data is safe and secured in the web-site, and helps you to
                            operate anywhere as it supports web - based.All important documents and processes are hassle - free such as tax collection processes, birth, marriage, death certificates, various bill request and many
                            other types of all certificates which can be issued & generated by Gram Panchayat as per government format.
                        </p>
                        <p>
                            A click is all it takes to manage the web-site with a simple user - friendly interface, and to streamline operations smoothly.
                        </p>
                        <a href="products.html" class="btn btn-primary">KNOW MORE</a>
                    </div>
                    <div class="col-sm-12 col-md-12 col-lg-6">
                        <img src="images/dashboard-about.png" alt="" class="img-fluid mt-3">
                    </div>
                </div>

            </div>
        </div>
    </div>

    <!-- FUN FACT -->
    <div class="section bgi-cover-center" data-background="images/dummy-img-1920x900-3.jpg">
        <div class="content-wrap">
            <div class="container">


            </div>
        </div>
    </div>

    <!-- FAQS -->
    <div class="section">
        <div class="content-wrap pb-0">
            <div class="container">

                <div class="row">

                    <div class="col-sm-12 col-md-12">
                        <h1 class="section-heading">
                            We Know The Difference Between “Completion” and “Satisfaction”.
                        </h1>
                    </div>
                </div>

                <div class="row align-items-end mt-5">
                    <div class="col-sm-12 col-md-12 col-lg-12">

                        <p>'Digital Gram Panchayat' is a Software specially developed for Gram Panchayat, to make them digitally equipped. In this software, all Gram Panchayat’s work can be done easily. By use of this Software 'Gram Samiti' operations can
                            work swiftly and will process the work very easily. There is no type of paperwork that needs to be made. All tax collection processes of Gram Panchayat Samiti can be managed by this software from birth certificate to marriage
                            certificate, and many other essential certificates necessary for the development.
                        </p>

                        <p class="uk21 mt-5 text-black">Vision</p>

                        <p>
                            To make all Gram Panchayat Samiti's work very easy by providing a user-friendly system to manage all their work and halt the paperwork.
                        </p>

                        <p class="uk21 mt-5 text-black">Mission</p>

                        <p>
                            To make all Gram Panchayat DIGITAL with 'Digital Gram Panchayat Software'. Speed up the work of Panchayat Samiti and make work error-free.
                        </p>

                    </div>

                </div>

            </div>
        </div>
    </div>
   
     <!-- MAPS -->
     <div class="maps-wraper">
        <div id="cd-zoom-in"></div>
        <div id="cd-zoom-out"></div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7436.346915047946!2d70.34933428744634!3d21.264600420186788!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bfd52177f24435b%3A0xaf9819a1de6c0926!2sAjab%2C%20Gujarat%20362229!5e0!3m2!1sen!2sin!4v1686116626578!5m2!1sen!2sin" width="100%" height="550" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div>

    <footer id="footer"></footer>




    <footer id="footer"></footer>

    <!-- JS VENDOR -->
    <script src="js/vendor/jquery.min.js"></script>
    <script src="js/vendor/bootstrap.min.js"></script>
    <script src="js/vendor/owl.carousel.js"></script>
    <script src="js/vendor/jquery.magnific-popup.min.js"></script>

    <!-- SENDMAIL -->
    <script src="js/vendor/validator.min.js"></script>
    <script src="js/vendor/form-scripts.js"></script>

    <script src="js/script.js"></script>

    

</body>

</html>

<?php
echo $hf;
?>