<?php
session_start();
if(isset($_SESSION['email']))
{
include 'includes/header.php';

include 'includes/topbar.php';
?>
<section>
	<div class="body">
		<div id="content" class="full">
			<div class="container">
			<h2 class="section-heading">
                            Namaste!
                        </h2>
                        <p class="subheading mb-4">"We assist in sustaining rural development through technology"</p>
                        <p>
                        The  The web-site is essential to support Digital India making Rural people's life easy and hassle-free, and helping them in development.
                        </p>
                        <p>
                            The Gram Panchayat web-site is specially developed for Gram Panchayat to support Digital India. It helps you to run all Gram Panchayat's operations smoothly and makes the process very easy. All data is safe and secured in the web-site, and helps you to
                            operate anywhere as it supports web - based.All important documents and processes are hassle - free such as tax collection processes, birth, marriage, death certificates, various bill request and many
                            other types of all certificates which can be issued & generated by Gram Panchayat as per government format.
                        </p>
                        <p>
                            A click is all it takes to manage the web-site with a simple user - friendly interface, and to streamline operations smoothly.
                        </p>
				</div>
			</div>
		</div>
	</div>
</section>

<?php
  include 'includes/footer.php';
}
  else
	header("Location:index.php");

?>